apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi # dummy, size is elastic
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # should be empty in static
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-e8a95a42 # change to my EFS volume ID

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    purpose: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html # Path inside the container
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b # select node as us-east-1b region 
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: efs-static # Must match the PVC name above

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-efs-static
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007