apiVersion: v1
kind: Pod
metada:
  name: resources-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      request:
        memory: "68Mi"
        cpu: "100m" # 1/10th of cpu
        # provide equal or more than requests
      limits:
        memory: "100Mi"
        cpu: "120m"

